### PR TITLE
Type Writer Effect on Home Page Title and small fix in Readme.md 

### PR DESCRIPTION
**Pull request by avleen123**
There was a small typo error in running the project locally part.

### CODE REVIEW

**Comment by jayk-gupta** [comment]
what is the typo?

**Comment by avleen123** [comment]
can you review @jayk-gupta

**Comment by jayk-gupta** [comment]
increase speed and add a blinking cursor

**Comment by avleen123** [comment]
> increase speed and add a blinking cursor

I have successfully did the required changes, have a look @jayk-gupta 
Here is a demo video for the same

https://github.com/jayk-gupta/web-resources-project/assets/52206641/301b3b30-43a3-4c02-b4cb-bb7972f29065

**Comment by avleen123** [comment]
Have a look @jayk-gupta

**Pull request merged**
