### PR TITLE
feat: ReDesigned the homePage 

### LINKED ISSUE #500: [STYLE]: Re-Designing the homePage
### Is your feature request related to a problem? Please describe
The current homepage does not contain any valuable points or meaningful content. The Landing page should describe what the current website is meant for and its functionalities. But unfortunately, we don't have any feature at all.

### Describe the solution you'd like

1. User-Friendly Design: The landing page should have an intuitive and visually appealing design to engage users and encourage them to explore the available resources.
2. Resource Categories: Organize the resources into distinct categories, such as HTML, CSS, JavaScript, frameworks, and libraries, allowing users to quickly find relevant learning materials.
3. Search Functionality: Implement a search feature that enables users to search for specific topics, tutorials, or keywords within the available resources.
4. Featured Content: Highlight key resources, tutorials, or projects on the landing page to provide immediate value and showcase the breadth of available learning materials.
5. Responsive Design: Ensure that the landing page is fully responsive, providing an optimal user experience across different devices and screen sizes.
6. Social Sharing: Include social sharing buttons to allow users to easily share the resources they find useful with their network, promoting the platform and its content.

### Additional context

I would like to work under GSSoC'23
Please assign me this issue

### PR DESCRIPTION
**Pull request by senthil-k8s**
Added navbar, feature section and footer section in homePage

closes #500

### CODE REVIEW

**Comment by senthil-k8s** [comment]
@jayk-gupta homePage Design done and new pages will be added in future for each nav link.

**Comment by jayk-gupta** [comment]
Please show the design here as image

**Comment by senthil-k8s** [comment]
I developed the homePage using common sections like navbar, hero, feature, footer. Each section is treated as container, i made it entirely from scratch. Each container is a feature. I made more than 2 containers. I'll add the ss of the preview

**Comment by senthil-k8s** [comment]
https://github.com/senthil-k8s/image/assets/93466587/8a540231-1f67-4d3e-ba82-892949f6e2db
https://github.com/senthil-k8s/image/assets/93466587/f1c5f182-74c8-47df-adf4-89b458dda353

**Comment by jayk-gupta** [comment]
The color scheme was of previous design which I have removed.
The color scheme will be according to the nav
PUll the changes in your repo

**Pull request closed without merging**
