### PR TITLE
Added new resource : Learning react book

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Book is added under the books section as a new resource.
name - learning react

closes the issue #183 please check @jayk-gupta

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please check the PR @jayk-gupta  I have added the resource

**Review by jayk-gupta — APPROVED** [review]

**Comment by Abhinavcode13** [comment]
Can you please merge it @jayk-gupta

**Comment by Abhinavcode13** [comment]
@jayk-gupta ??

**Comment by Abhinavcode13** [comment]
Will it be merged @jayk-gupta

**Comment by jayk-gupta** [comment]
Please read this:
[Important Update](https://github.com/jayk-gupta/web-resources-project/discussions/208)

**Pull request closed without merging**
