### PR TITLE
books are added

### PR DESCRIPTION
**Pull request by Sushilverma002**
close issue-> #561 
image

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@jayk-gupta have a look.

**Comment by Sushilverma002** [comment]
@jayk-gupta sir please review

**Comment by Sushilverma002** [comment]
@jayk-gupta

**Comment by Sushilverma002** [comment]
@jayk-gupta please merge it

**Comment by Sushilverma002** [comment]
@jayk-gupta have a look

**Comment by Sushilverma002** [comment]
@jayk-gupta have a look

**Comment by Sushilverma002** [comment]
@jayk-gupta

**Comment by Sushilverma002** [comment]
@jayk-gupta please merge it so that I will work on a new issue.

**Comment by jayk-gupta** [comment]
Eloquent one is already there

**Comment by Sushilverma002** [comment]
it is different from that book its third edition.

**Comment by Sushilverma002** [comment]
@jayk-gupta

**Comment by Sushilverma002** [comment]
@jayk-gupta i removed that book and now only 1 book that is react for 30days is there

**Comment by Sushilverma002** [comment]
@jayk-gupta

**Comment by Sushilverma002** [comment]
@jayk-gupta please merge it.

**Pull request merged**
