### PR TITLE
feat: Added Programiz Details in html.json and javascript.json Files in websites Category

### PR DESCRIPTION
**Pull request by NarendraKoya999**
### Description:
- Added Programiz Details in html.json and javascript.json Files. for Learning Both HTML and JavaScript Courses Beginner's Friendly.
- This course is Free to Use.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @jayk-gupta . Please Review on this PR. My JSON Format is well and Good. But, Did not Pass JSON Validation.

**Comment by NarendraKoya999** [comment]
> w3schools already there

@jayk-gupta . Basically, Yesterday I got Merge Conflicts in Each File. So, that's why w3schools in My PR changes List. That is actually Happened .I did not created any w3schools Resources Details.

**Comment by jayk-gupta** [comment]
Still two conflicts there, do resolve them

**Comment by NarendraKoya999** [comment]
> Still two conflicts there, do resolve them

Resolved Merge Conflicts .Please Check ?

**Pull request merged**
