### PR TITLE
Fixed : issue  #281

### PR DESCRIPTION
**Pull request by parthpathakpp1**
I changed the Books images in Books section . 

**Before**

https://github.com/jayk-gupta/web-resources-project/assets/85991449/026a1797-e08f-4cbf-8abf-29e5fbd70b2f

**After**

https://github.com/jayk-gupta/web-resources-project/assets/85991449/32852f95-a759-4f0e-aed7-7513658436b7

### CODE REVIEW

**Comment by parthpathakpp1** [comment]
@jayk-gupta can you please check this PR .

**Comment by parthpathakpp1** [comment]
> I changed the Books images in Books section .
> 
> **Before**
> 
>  weresourceibeforeiss.mp4 
> **After**
> 
>  webresourcesimgissuehopefullyfixed.mp4

@jayk-gupta Can you please check the PR .

**Comment by jayk-gupta** [comment]
There is merge conflict, please resolve it!

**Comment by parthpathakpp1** [comment]
> There is merge conflict, please resolve it!

@jayk-gupta Resolve the conflict. Please Check.

**Comment by jayk-gupta** [comment]
why the image links are so big?

**Pull request closed without merging**
