### PR TITLE
Added animation on all cards images

### PR DESCRIPTION
**Pull request by parasss19**
## Closes Issue #544 

-Added hover animation on each cards images

## Screenshot

https://github.com/jayk-gupta/web-resources-project/assets/101205226/269d6cfe-cf38-445d-ab31-f31a25c72e7a

### CODE REVIEW

**Comment by jayk-gupta** [comment]
animation is good but what is the need of decreasing the size of image, it should  actually increase so that user it able to see it.

**Comment by parasss19** [comment]
> animation is good but what is the need of decreasing the size of image, it should actually increase so that user it able to see it.

I can make it zoom out on hover but thr point is when we hover it wi increase the size of image due to which it hide the title of the card and user are more interested in reading the title

**Comment by jayk-gupta** [comment]
Yes ,then what to do?

**Comment by parasss19** [comment]
> Yes ,then what to do?

In my opinion it's looking good

**Pull request merged**
