### PR TITLE
tutorial point section is added in website

### PR DESCRIPTION
**Pull request by Sushilverma002**
close issue -> #454 
image

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@jayk-gupta have a look please!!!

**Comment by Sushilverma002** [comment]
@jayk-gupta

**Comment by Sushilverma002** [comment]
@jayk-gupta have a look!!!!!

**Comment by Sushilverma002** [comment]
@jayk-gupta sir please merge it.

**Comment by Sushilverma002** [comment]
@jayk-gupta please merge it

**Comment by jayk-gupta** [comment]
There are conflicts ,please resolve it

**Comment by Sushilverma002** [comment]
@jayk-gupta resolved please merge it.

**Comment by Sushilverma002** [comment]
@jayk-gupta please merge it

**Comment by Sushilverma002** [comment]
@jayk-gupta HAVE A LOOK!!!!!!!!!

**Comment by Sushilverma002** [comment]
@jayk-gupta please merge

**Pull request merged**
