### PR TITLE
added hamburger option to sidebar

### PR DESCRIPTION
**Pull request by Akanksha-202**
image
image

Added the hamburger option successfully. Kindly review and comment if any extra changes are required:)
In accordance to issue #49

### CODE REVIEW

**Comment by jayk-gupta** [comment]
The changes are not being shown on locally running your forked repo.
Also update your branch first.

**Comment by Akanksha-202** [comment]
Updated my branch and the changes are there if running locally my cloned repo but in "hamburger" branch and not in the main
Switch to hamburger branch then you'll see the changes

**Comment by jayk-gupta** [comment]
Ohk I will see!

**Comment by jayk-gupta** [comment]
Still its not showing the code!
Merge it in main

**Comment by Akanksha-202** [comment]
Done!
Now everything is in my main branch too

**Comment by jayk-gupta** [comment]
Okay!

**Comment by jayk-gupta** [comment]
Please work on it and push to dev branch
**NOTE**
The contributing guidelines have changed so please make a new PR to dev branch.
Checkout the contributing.md file for more details.
Do not make any PR on the Main branch.

**Pull request closed without merging**
