### PR TITLE
feat: Added Studytonight Details in 3 Files in websites Category

### PR DESCRIPTION
**Pull request by NarendraKoya999**
### Changes Proposed
- Added Studytonight Details in html.json, css.json and javascript.json Files in websites Category.
- This Studytonight Website Offering Multiple Type of Options created like Challenges, Learning Paths Etc.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @jayk-gupta . Please Review on this PR. My JSON Format is well and Good. But, Did not Pass JSON Validation.

**Comment by jayk-gupta** [comment]
resolve the merge conflicts

**Comment by NarendraKoya999** [comment]
Hi @jayk-gupta . I resolved Merge Conflicts. Please Check ?

**Comment by jayk-gupta** [comment]
please resolve conflicts

**Comment by NarendraKoya999** [comment]
> please resolve conflicts

Solved Merge Conflicts. Please Check @jayk-gupta

**Comment by jayk-gupta** [comment]
json file is not correct

**Pull request merged**
