### PR TITLE
added the twitter share icon

### PR DESCRIPTION
**Pull request by tanujbordikar**
### `Under GSSOC'23`
- Closes issue #584 

In this PR, i have added a twitter share icon in the Card.jsx for sharing purpose.
Screenshot:
share

### CODE REVIEW

**Comment by tanujbordikar** [comment]
Closes #584

**Comment by jayk-gupta** [comment]
It will open in twitter only?
or we can share it anywhere?

**Comment by tanujbordikar** [comment]
> It will open in twitter only? or we can share it anywhere?

It will open it Twitter only!

**Comment by tanujbordikar** [comment]
hey @jayk-gupta , can you review it and merge this pull request.

**Comment by jayk-gupta** [comment]
It would be better if we can share it anywhere including twitter!

**Pull request closed without merging**
