### PR TITLE
Added Navbar using Framer Motion

### PR DESCRIPTION
**Pull request by adarshgupta404**
Dependency issues were found in react-icons icons so chose the different icons for it. Please make it level 3

### CODE REVIEW

**Comment by adarshgupta404** [comment]
@jayk-gupta

**Comment by jayk-gupta** [comment]
please add  a video of its working

**Comment by adarshgupta404** [comment]
> please add  a video of its working

Already sent please check the discord

**Comment by adarshgupta404** [comment]
> please add a video of its working

https://github.com/jayk-gupta/web-resources-project/assets/112967201/57bf34f7-f871-4be7-bb22-e016b05bc61f

**Comment by jayk-gupta** [comment]
Hey, please pull the changes before pushing your code.
Check the website the UI has changed and also the code structure

**Pull request closed without merging**
